### ISSUE TITLE
wiki 재정리

### ISSUE THREAD

**Issue by dingdongx2** [BD-SEARCH/MLtutorial#4]
01. 순서가 뒤죽박죽
* 체계적으로 바꿀 필요
02. 내용 더 추가 및 정리

**Comment by warmwall** [comment]
* CNN이나 RNN 등은 기본 딥러닝 페이지로 옮기기(?)
* GAN이나 Attention Mechanism 등 유명한 것들 보충 필요

3. 잘못된 내용이 있는지 점검 후 교정

**Comment by dingdongx2** [comment]
저번에 나왔던 의견 중 **스터디 때 모여서 각자 하나의 주제에 대해서 정리하자**가 있었음
그 때 GAN, Attention Mechanism에 대해 정리하면 좋을 것 같다고 생각

**Comment by dingdongx2** [comment]
* Wiki main page와 우측 메뉴를 동시에 수정해야 하는 불편함이 있음
  * 한 쪽을 단순화할 필요가 있다고 생각
* 페이지에 따로 작성한 내용 링크 거는 방식, 외부 참고 레퍼런스 링크 거는 방식을 확실히 해야 할 것 같음

**Comment by warmwall** [comment]
- 논문 위키에 MLTutorial 위키의 페이지와 연관 있은 페이지가 있다면 서로 링크를 걸어 두는 것도 좋을 것 같음
  - 예: MLTutorial 위키에서 GAN을 보다가 관련 논문을 보고 싶으면, 논문 위키 링크를 눌러 바로 확인하기

- 메인 페이지와 사이드바 내용을 자동으로 동일하게 유지하려면 preprocessor를 이용헤야 함
- 논문 위키 구조 개선 필요...

**Comment by warmwall** [comment]
논문 위키 페이지 구성 Example

- NLP: 임베딩, 응용
- 비전: 임베딩, 응용
- GAN

**Comment by warmwall** [comment]
* 학회별로 나눠서 논문 정리하기로 함.
* 논문 정리하는 양식 확정. 학회명 및 연도, 제1저자도 같이 적기로 함

위키 주소: https://github.com/BD-SEARCH/Study2019/wiki/IEEE
